### ISSUE TITLE
Order rejects with a string instead of a DriveWealthError

### ISSUE THREAD

**Issue by jjshammas** [DriveWealth/drivewealth-javascript#1]
https://github.com/DriveWealth/drivewealth-javascript/blob/caee18b56f5132d241249fc4df3c0f61364e9e5f/src/Order.js#L228

**Comment by timurtu** [comment]
Like this?

```javascript
if (order.rejectionReason !== undefined) {
    return reject(new DriveWealthError(order.rejectionReason));
}
```

It comes out to this format,

```javascript
{ 
DriveWealthError: 0607 Insufficient funds. EHHJ000013 accountNo=DPAK000032 accountCash= 2552.79 totalRequiredEquity= 5002.98 commission=-2.99 sumRestingNotional=0 sumRestingComission=0 ordersInStreet=
        at /Users/timur/repos/drivewealth-javascript/lib/drivewealth.js:1114:26
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:169:7)
      name: 'DriveWealthError',
      body: undefined,
      statusCode: undefined,
      headers: undefined 
}
```

I'm not sure if the other fields should be filled or if they should be removed if undefined in the `DriveWealthError` constructor

**Comment by jjshammas** [comment]
You need to send back the body, statusCode, and headers

**Comment by timurtu** [comment]
Okay got it the statusCode may be unclear in this scenario because the request succeeds with an ordRejReason
